blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/picklebooking/rallyhub
    about: Check the README for common questions
  - name: Discussions
    url: https://github.com/picklebooking/rallyhub/discussions
    about: Ask questions and discuss ideas
